#!/usr/bin/env python3
"""Generate the browser-friendly catalog JS from data/catalog.json.

This keeps the static GitHub Pages build and optional Python backend on the same source of truth.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "data" / "catalog.json"
OUT = ROOT / "assets" / "js" / "catalog-data.js"


def main() -> None:
    payload = json.loads(CATALOG.read_text(encoding="utf-8"))
    products = payload.get("products")
    if not isinstance(products, list) or not products:
        raise SystemExit("catalog.json must contain a non-empty products list")

    ids = [item.get("id") for item in products]
    if len(ids) != len(set(ids)):
        raise SystemExit("duplicate product ids in catalog.json")

    js = (
        "// AUTO-GENERATED by scripts/build_catalog.py. Edit data/catalog.json instead.\n"
        "window.CASEIRINHOS_CATALOG = "
        + json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
        + ";\n"
    )
    OUT.write_text(js, encoding="utf-8")
    print(f"generated {OUT.relative_to(ROOT)} with {len(products)} products")

if __name__ == "__main__":
    main()
